import { NextRequest } from 'next/server';
import { loadouts } from '@/data/loadouts';
import { jsonResponse, errorResponse, optionsResponse } from '../cors';

export function OPTIONS() { return optionsResponse(); }

export async function POST(request: NextRequest) {
  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return errorResponse('Invalid JSON body');
  }

  const { loadout_slug, agent_name, agent_emoji, model, port } = body as {
    loadout_slug?: string;
    agent_name?: string;
    agent_emoji?: string;
    model?: string;
    port?: number;
  };

  if (!loadout_slug || !agent_name) {
    return errorResponse('Missing required fields: loadout_slug, agent_name');
  }

  const loadout = loadouts.find(l => l.slug === loadout_slug);
  if (!loadout) {
    return errorResponse('Loadout not found', 404);
  }

  const emoji = agent_emoji || '🤖';
  const agentModel = model || 'claude-sonnet-4';
  const agentPort = port || (3100 + Math.floor(Math.random() * 900));
  const agentSlug = agent_name.toLowerCase().replace(/[^a-z0-9]+/g, '-');

  const soul = `# ${emoji} ${agent_name} — SOUL.md

${loadout.sampleSoul}

## Loadout: ${loadout.name} ${loadout.emoji}
${loadout.description}

## Core Tools
${loadout.coreTools.map(t => `- **${t.name}**: ${t.description}`).join('\n')}

## Workflows
${loadout.workflows.map(w => `- **${w.name}** (${w.trigger}): ${w.description}`).join('\n')}
`;

  const agents = `# AGENTS.md — ${agent_name}

Generated by OpenClaw Equipment for the **${loadout.name}** loadout.

## Quick Start
1. Read SOUL.md — that's who you are
2. Check your tools and skills
3. Start helping

## Tools
${loadout.coreTools.map(t => `- ${t.name}`).join('\n')}
`;

  const config = {
    name: agent_name,
    slug: agentSlug,
    emoji,
    model: agentModel,
    port: agentPort,
    loadout: loadout.slug,
    gateway: {
      host: '127.0.0.1',
      port: agentPort,
    },
  };

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.openclaw.agent.${agentSlug}</string>
  <key>ProgramArguments</key>
  <array>
    <string>openclaw</string>
    <string>gateway</string>
    <string>start</string>
    <string>--port</string>
    <string>${agentPort}</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
</dict>
</plist>`;

  const deploy_script = `#!/bin/bash
# Deploy ${agent_name} (${loadout.name} loadout)
set -e

AGENT_DIR="$HOME/.openclaw/agents/${agentSlug}"
mkdir -p "$AGENT_DIR/workspace"

echo "Writing config files..."
cat > "$AGENT_DIR/workspace/SOUL.md" << 'SOUL_EOF'
${soul}
SOUL_EOF

cat > "$AGENT_DIR/workspace/AGENTS.md" << 'AGENTS_EOF'
${agents}
AGENTS_EOF

cat > "$AGENT_DIR/openclaw.json" << 'CONFIG_EOF'
${JSON.stringify(config, null, 2)}
CONFIG_EOF

echo "✅ ${agent_name} deployed to $AGENT_DIR"
echo "Start with: openclaw gateway start --port ${agentPort}"
`;

  return jsonResponse({ soul, agents, config, plist, deploy_script });
}
